[package]
name = "schemadb"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem schemadb"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.38"
once_cell = "1.7.2"
diem-logger = { workspace = true }
diem-metrics = { workspace = true }
#rocksdb = { workspace = true }

# OpenBSD and MSVC are unteested and shouldn't enable jemalloc:
# https://github.com/tikv/jemallocator/blob/52de4257fab3e770f73d5174c12a095b49572fba/jemalloc-sys/build.rs#L26-L27
[target.'cfg(any(target_os = "openbsd", target_env = "msvc"))'.dependencies.rocksdb]
default-features = false
features = ["snappy"]
git = "https://github.com/rongma7/rust-rocksdb"
rev = "9183fa9"

[target.'cfg(not(any(target_os = "openbsd", target_env = "msvc")))'.dependencies.rocksdb]
default-features = false
features = ["snappy", "jemalloc"]
git = "https://github.com/rongma7/rust-rocksdb"
rev = "9183fa9"

[dev-dependencies]
byteorder = "1.4.3"
proptest = "1.0.0"
diem-temppath = { workspace = true }
