[package]
description = "Conflux core storage library"
homepage = "https://www.confluxnetwork.org"
license = "GPL-3.0"
name = "storage2"
version = "1.0.0"
edition = "2021"

[dependencies]
cfx-storage2 = { git = "https://github.com/Conflux-Chain/cfx-storage2.git", rev = "d9427fc" }
ethereum-types = { workspace = true }
parking_lot = { workspace = true }
cfx-internal-common = { workspace = true }
cfx-types = { workspace = true }
primitives = { workspace = true }
tiny-keccak = { workspace = true }
amt = { git = "https://github.com/Conflux-Chain/amt", rev = "387995a", features = ["bls12-381"] }
once_cell = { workspace = true }
ark-bls12-381 = "0.5"
kvdb-rocksdb = { git = "https://github.com/Conflux-Chain/parity-common-rocksdb", rev = "2e60465", version = "0.17.0-iter-nochecksum-partitionedindexfilter" }
cfx-db-errors = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
log = { workspace = true }